version: '2'
services:
    web:
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./code:/code
        - ./conf.d:/etc/nginx/conf.d
      depends_on:
        - php56
        - php71
        - mysql
        - phpmyadmin
      networks:
        default:
          ipv4_address: 172.21.0.9
    php56:
      image: cytopia/php-fpm-5.6
      volumes:
        - ./code:/code
        - ./php.d:/etc/php-custom.d
      links:
        - "mysql:dbhost"
    php71:
      image: cytopia/php-fpm-7.1
      volumes:
        - ./code:/code
        - ./php.d:/etc/php-custom.d
      links:
        - "mysql:dbhost"
    mysql:
      image: mariadb:latest
      environment:
          - MYSQL_DATABASE=bitrix3
          - MYSQL_ROOT_PASSWORD=123
          - MYSQL_USER=bitrix
          - MYSQL_PASSWORD=123
      volumes:
        - ./database:/var/lib/mysql
      ports:
        - "3301:3306"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
        - PMA_HOST=mysql
        - PMA_USER=bitrix
        - PMA_PASSWORD=123
      volumes:
        - /sessions
networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.21.0.0/16
         gateway: 172.21.0.1
